_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

max_epochs: 50000

accelerator: gpu
devices: 1

# mixed precision for extra speed-up
precision: bf16-mixed

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
val_check_interval: 1.0

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

log_every_n_steps: 50
accumulate_grad_batches: 32

gradient_clip_val: 1.0
