_target_: src.models.vox2smiles.VoxToSmilesModel
config:
  hidden_size: 768
  num_hidden_layers: 8
  num_attention_heads: 8
  intermediate_size: 3072
  hidden_act: "gelu"
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  initializer_range: 0.02
  layer_norm_eps: 1e-12
  image_size: [32, 32, 32]
  patch_size: 4
  num_channels: 9
  qkv_bias: True
  encoder_stride: 2
  lr: 1e-3
  torch_dtype: "bfloat16"
  scheduler:
    type: "warmup_stable_decay"  # Options: step, linear, cosine, cosine_with_restarts, etc.
    num_warmup_steps: 300
    num_stable_steps: 200000
    num_decay_steps: 200000
    min_lr_ratio: 0.05
    interval: "step"
