_target_: src.models.vox2smiles.VoxToSmilesModel
config:
  hidden_size: 768
  num_hidden_layers: 8
  num_attention_heads: 8
  intermediate_size: 3072
  hidden_act: "gelu"
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  initializer_range: 0.02
  layer_norm_eps: 1e-12
  image_size: [32, 32, 32]
  patch_size: 4
  num_channels: 9
  qkv_bias: True
  encoder_stride: 2
  lr: 5e-5 
  scheduler:
    type: "cosine_with_min_lr"  # Options: step, linear, cosine, cosine_with_restarts, etc.
    num_warmup_steps: 100
    min_lr_rate: 0.1
    num_training_steps: 20_000
    interval: "step"  # or "epoch"
    frequency: 1