_target_: src.models.vox2smiles.VoxToSmilesModel
config:
  hidden_size: 768
  num_hidden_layers: 8
  num_attention_heads: 8
  intermediate_size: 3072
  hidden_act: "gelu"
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  initializer_range: 0.02
  layer_norm_eps: 1e-12
  image_size: [32, 32, 32]
  patch_size: 4
  num_channels: 10
  qkv_bias: True
  encoder_stride: 2
  lr: 5e-5 