# Main configuration file for Hydra

# Default mode
mode: train_end2end

# Paths
paths:
  pdb_dir: ../PDBbind_v2020_refined-set
  val_pdb_dir: ../validation_PDBbind
  voxmiles_data_path: ../geom/rdkit_folder/drugs
  output_dir: ./outputs
  checkpoints_dir: ./checkpoints
  img_save_dir: ./images

# Random seed
seed: 42

# Default configurations
defaults:
  - data: poc2smiles_data
  - model: poc2smiles
  - training: train_end2end
  - _self_ 