defaults:
  - _self_
  - data: data.yaml
  - model: poc2mol.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "poc2mol"
tags: ["dev"]
train: True
test: True
optimized_metric: "val/loss"
ckpt_path: null # over-ride this to resume training
seed: 42