defaults:
  - _self_
  - data: poc2mol_plinder_data
  - model: poc2mol
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - experiment: null

task_name: "poc2mol"
tags: ["dev"]
train: True
test: True
optimized_metric: "val/loss"
ckpt_path: null # over-ride this to resume training
seed: 42